fix to bug regarding same icon for multiple fusions
infinitefusion/infinitefusion-e18 pull request #88
Opened 2023-05-09 17:16 UTC by Jodiark

What is the bug?
If multiple Pokemon are fused with the same head, then all of their icons e.g. in the PC or the party will be the same.

How can this bug be reproduced?
Catch multiple of the same Pokemon, e.g. pidgey, and several different Pokemon. Now fuse all but one of the pidgeys so that all fusions have pidgey as the head. Now all pokemon with pidgey as the head should have the same icon, even though they are completely different pokemon.

What is the cause of this issue?
There are three functions with the name 'createFusionIcon' in three different files: 'Scripts/013_Items/004_1_PokeradarUI.rb', 'Scripts/014_Pokemon/001_Pokemon-related/003_Pokemon_Sprites.rb' and 'Scripts/016_UI/017_UI_PokemonStorage.rb'.
These functions are used to create the icons. They currently do this by loading the head-icon, editing it with half of the body-icon and returning the icon. This causes all pokemon that use the head-icon to use this new icon.

What is the solution to this problem?
The head-icon must not be edited. Instead, a new icon for the fusion needs to be created.
I have never programmed in Ruby before, so I have been very careful with my changes. I have modified the 'createFusionIcon'-function, so that it copies the icon-file of the head-pokemon to a new folder. This new file is then loaded and edited to have half of the body-icon.
This solution isn't optimal because new files are created everytime a fusion-icon is created. A better solution would be to create a new empty AnimatedBitmap object and copy half of each icon onto this new temporary object. However, the AnimatedBitmap-constructor currently doesn't allow the creation of an empty icon and I don't have enough experience with either Ruby or the Project to foresee any issues that may arise.

I wasn't able to test the changes in the development environment as some files appear to be missing from the github-repository. The changes work in my normal game directory.  It may be necessary to add the following directory: 'Graphics/Pokemon/FusionIcons'.

2023-06-10 22:55 UTC, kurayamiblackheart requested changes
Will crash without checking if dir exist.

2023-06-10 22:55 UTC, kurayamiblackheart commented on Data/Scripts/016_UI/017_UI_PokemonStorage.rb
> +    dexNum = getDexNumberForSpecies(species)
```
    directory_name = "Graphics/Pokemon/FusionIcons"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
```
needs to be added, to check if directory exist, and create it if it doesn't exist. Game will crash without this code if the dir doesn't exist !

2023-06-10 22:55 UTC, kurayamiblackheart commented on Data/Scripts/014_Pokemon/001_Pokemon-related/003_Pokemon_Sprites.rb
```
    directory_name = "Graphics/Pokemon/FusionIcons"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
```
needs to be added, to check if directory exist, and create it if it doesn't exist. Game will crash without this code if the dir doesn't exist !

2023-06-10 22:55 UTC, kurayamiblackheart commented on Data/Scripts/013_Items/004_1_PokeradarUI.rb
```
    directory_name = "Graphics/Pokemon/FusionIcons"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
```
needs to be added, to check if directory exist, and create it if it doesn't exist. Game will crash without this code if the dir doesn't exist !

2023-06-12 05:53 UTC, kurayamiblackheart commented
#90 patch this issue correctly (create the FusionIcons folder if it doesn't exist)

2023-07-01 21:41 UTC, infinitefusion commented
> #90 patches this issue correctly (create the FusionIcons folder if it doesn't exist)
Please don't close pull requests by other people

2023-07-01 21:42 UTC, infinitefusion approved these changes

2023-07-01 21:43 UTC, merged